baseURL: https://secfirst.org
title: Security First
menu:
  # main menu (top)
  main:
  - name: home
    url: /
    weight: 1
  - name: umbrella
    url: /umbrella/
    weight: 2
  - name: docs
    url: /umbrella-manual/
    weight: 3
  - name: tent
    url: /tent/
    weight: 3
  - name: training
    url: /training/
    weight: 4
  - name: about
    url: /about/
    weight: 5
  - name: faq
    url: /faq/
    weight: 6
  - name: contribute
    url: /contribute/
    weight: 7
  - name: blog
    url: /blog/
    weight: 8
  - name: contact
    url: /contact/
    weight: 9
  # product menu (bottom)
  product:
  - name: umbrella
    url: /umbrella/
    weight: 1
  - name: tent
    url: /tent/
    weight: 2
  - name: training
    url: /training/
    weight: 3
  # info menu (bottom)
  info:
  - name: legal & ethical
    url: /legal/
    weight: 1
  - name: terms & conditions
    url: /terms/
    weight: 2
  - name: privacy
    url: /privacy/
    weight: 3
  - name: code of conduct
    url: /conduct
    weight: 4
  # company menu (bottom)
  company:
  - name: about
    url: /about/
    weight: 1
  # - name: mission
  #   url: /mission/
  #   weight: 2
  - name: principles
    url: /about/
    weight: 3

languages:
  en:
    languageName: "eng"
    weight: 1
    params:
      flag: "US"

markup:
  TableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

